version: '3.9'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_service
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html
    networks:
      - service_network
      
networks:
  service_network:
    external: true

volumes:
  mysql_data:
